# Generated by Django 4.2.17 on 2025-01-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_condition',
            field=models.CharField(choices=[('GROUNDED', 'Grounded'), ('MAINTENANCE', 'Needs Maintenance'), ('MINOR_ISSUES', 'Minor Issues'), ('GOOD', 'Good Condition'), ('AIRWORTHY', 'Airworthy')], default='AIRWORTHY', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='flight_photos/'),
        ),
        migrations.AddField(
            model_name='flight',
            name='registration_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
