# Generated by Django 4.2 on 2025-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flight_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='distance',
            field=models.IntegerField(default=0, help_text='Distance in nautical miles'),
        ),
    ]
